### ISSUE TITLE
Pop-ups

### ISSUE THREAD

**Issue by reevespaul** [japanese-wiki-corpus/japanese-wiki-corpus.github.io#1]
Each time I search for something the server tries to create popup windows instead of either opening the response in the same page, or opening it in a new tab. 

Most web developers stopped doing popups over 20 years ago. Popups were such an annoyance that most web-browsers disable them by default. I haven't come across a site that does popups for so long now that I forgot they ever existed. You hava a great resource here that is really spoilt by this.

If you are not sure what I mean try using the site with Firefox and popups disabled.

**Comment by ac-yu** [comment]
Thanks for reporting an issue!
When I tried searching in Firefox with popups disabled, it didn't give any error messages. It only opened the search results on a new page.
It might be from an older version. Let me know if the problem still happens.

**Comment by reevespaul** [comment]
I tried it just now in Firefox 78.6.0esr and nothing annoyed me ( and I'm easily annoyed :-) ) 
Thanks!
