### ISSUE TITLE
Link to Japanese text please?

### ISSUE THREAD

**Issue by bolaurent** [japanese-wiki-corpus/japanese-wiki-corpus.github.io#2]
I just stumbled upon this and it looks very interesting.

But for advanced Japanese language learners, it would be much more useful if the English provided a link to the Japanese source text. I didn't see a way to get there.

**Comment by ac-yu** [comment]
Thanks for the suggestion! I agree that would be useful to have. I'll work on it :)

**Comment by ac-yu** [comment]
I've added the links to the Japanese pages. You can click on the Japanese title on the English pages or the link at the bottom of the page to get there. Let me know if there are any other issues.
