### ISSUE TITLE
javascript interferes with select or copy

### ISSUE THREAD

**Issue by bolaurent** [japanese-wiki-corpus/japanese-wiki-corpus.github.io#3]
As a Japanese learner, I often want to select some text and look it up in the system dictionary. 

Many Japanese pages seem to use javascript to prevent selecting or copying. 

This japanese-wiki-corpus seems to be doing something like that. For instance, if I visit https://www.japanese-wiki-corpus.org/jp/history/百円硬貨.html, then double click on 硬貨 in the title, that word is momentarily highlighted and then the highlight (and selection) disappears. I searched in the javascript but did not find the cause. However, if I disable javascript, then I can select and copy and lookup in dictionary normally.

Can this be fixed? The content is open sourced; there's no reason to try to protect it from copying.

**Comment by ac-yu** [comment]
Hi, thanks for reporting a bug, but I'm not able to repro this. When I double-click the text, it selects it and I'm able to copy it correctly.

I think my own javascript code (https://github.com/japanese-wiki-corpus/japanese-wiki-corpus.github.io/tree/master/assets/1.0) is only used for toggling the navigation bar and adding engagement buttons. 

To narrow down the problem, are you able to select and copy text in the main page (https://www.japanese-wiki-corpus.org/), and the categories page (eg. https://www.japanese-wiki-corpus.org/culture.html)?

**Comment by bolaurent** [comment]
Hmm. Now I cannot reproduce it either. Sorry to have troubled you!
